#!/bin/sh

# Copyright (c) 2023 Alex313031. All rights reserved.

set -e

# Update cache of .desktop file MIME types. Non-fatal since it's just a cache.
update-desktop-database > /dev/null 2>&1 || true
